version: '3'
services:

  web:
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

